# Generated by Django 3.0.3 on 2020-05-25 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('tag', models.TextField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('descripition', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('compare_price', models.IntegerField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 24, 10, 58, 16, 263275))),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
