# Generated by Django 3.0.3 on 2020-05-26 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 5, 59, 41, 827231)),
        ),
    ]
